---
 - name: This will install application
   yum: name={{item}} state=latest
   with_items: "{{ install }}"
   notify: 
   - restart apache2
#
# - name: start apache2
#   service: name=httpd state=started
